<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="3" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="655782" started-at="2015-09-01T07:26:58Z" finished-at="2015-09-01T07:37:54Z">
    <groups>
      <group name="Sanity IOS">
        <method signature="SanityIos.actions()[pri:0, instance:Native.SanityIos@1838ccb8]" name="actions" class="Native.SanityIos"/>
      </group> <!-- Sanity IOS -->
    </groups>
    <test name="Sanity Tests" duration-ms="655782" started-at="2015-09-01T07:26:58Z" finished-at="2015-09-01T07:37:54Z">
      <class name="Native.SanityIos">
        <test-method status="PASS" signature="setupBeforeSuite(org.testng.ITestContext)[pri:0, instance:Native.SanityIos@1838ccb8]" name="setupBeforeSuite" is-config="true" duration-ms="116466" started-at="2015-09-01T10:25:01Z" finished-at="2015-09-01T10:26:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[org.testng.TestRunner@54089484]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupBeforeSuite -->
        <test-method status="PASS" signature="checkHomeScreen()[pri:0, instance:Native.SanityIos@1838ccb8]" name="checkHomeScreen" is-config="true" duration-ms="2174" started-at="2015-09-01T10:26:58Z" finished-at="2015-09-01T10:27:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkHomeScreen -->
        <test-method status="FAIL" signature="actions()[pri:0, instance:Native.SanityIos@1838ccb8]" name="actions" duration-ms="54942" started-at="2015-09-01T10:27:00Z" description="Test the Actions" finished-at="2015-09-01T10:27:55Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Priority didn't display]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Priority didn't display
	at org.testng.Assert.fail(Assert.java:94)
	at Native.IosMethods.clickName(IosMethods.java:521)
	at Native.SanityIos.actions(SanityIos.java:378)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- actions -->
        <test-method status="PASS" signature="checkHomeScreen()[pri:0, instance:Native.SanityIos@1838ccb8]" name="checkHomeScreen" is-config="true" duration-ms="118963" started-at="2015-09-01T10:27:55Z" finished-at="2015-09-01T10:29:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkHomeScreen -->
        <test-method status="FAIL" signature="actions()[pri:0, instance:Native.SanityIos@1838ccb8]" name="actions" duration-ms="23159" started-at="2015-09-01T10:29:54Z" description="Test the Actions" finished-at="2015-09-01T10:30:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Done didn't display]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Done didn't display
	at org.testng.Assert.fail(Assert.java:94)
	at Native.IosMethods.clickName(IosMethods.java:521)
	at Native.SanityIos.actions(SanityIos.java:368)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- actions -->
        <test-method status="PASS" signature="checkHomeScreen()[pri:0, instance:Native.SanityIos@1838ccb8]" name="checkHomeScreen" is-config="true" duration-ms="213174" started-at="2015-09-01T10:30:17Z" finished-at="2015-09-01T10:33:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkHomeScreen -->
        <test-method status="FAIL" signature="actions()[pri:0, instance:Native.SanityIos@1838ccb8]" name="actions" duration-ms="243334" started-at="2015-09-01T10:33:50Z" description="Test the Actions" finished-at="2015-09-01T10:37:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[page 1 of 15 didn't display]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: page 1 of 15 didn't display
	at org.testng.Assert.fail(Assert.java:94)
	at Native.IosMethods.clickId(IosMethods.java:427)
	at Native.SanityIos.actions(SanityIos.java:407)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1049)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1254)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- actions -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:Native.SanityIos@1838ccb8]" name="tearDown" is-config="true" duration-ms="17604" started-at="2015-09-01T10:37:54Z" finished-at="2015-09-01T10:38:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- Native.SanityIos -->
    </test> <!-- Sanity Tests -->
  </suite> <!-- Suite -->
</testng-results>
