<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SGMacBookPROs-MacBook-Pro.local" name="Native.SanityIos" tests="2" failures="0" timestamp="6 Sep 2015 12:13:39 GMT" time="1010.420" errors="1">
  <testcase name="actions" time="475.559" classname="Native.SanityIos">
    <error type="com.applitools.eyes.NewTestException" message="&#039;iOS_Actions_Grid- QR_Success&#039; of &#039;iOS_SG&#039;. Please approve the new baseline at https://eyes.applitools.com/app/sessions/251960759741358">
      <![CDATA[com.applitools.eyes.NewTestException: 'iOS_Actions_Grid- QR_Success' of 'iOS_SG'. Please approve the new baseline at https://eyes.applitools.com/app/sessions/251960759741358
	at com.applitools.eyes.EyesBase.close(EyesBase.java:521)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at com.applitools.eyes.EyesBase.close(EyesBase.java:444)
	at com.applitools.eyes.Eyes.close(Eyes.java:22)
	at Native.IosMethods.eyesCheckWindow(IosMethods.java:93)
	at Native.SanityIos.actions(SanityIos.java:519)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- actions -->
  <testcase name="actions" time="534.861" classname="Native.SanityIos"/>
</testsuite> <!-- Native.SanityIos -->
